### ISSUE TITLE
[FEATURE] - Filter: Temporal Blur (frame blending)

### ISSUE THREAD

**Issue by couleurm** [FiniteSingularity/obs-composite-blur#100]
Hey, I've wrote up a suggestion for anyone to pick up if they find it interesting:

An OBS video filter that does frame blending, aka doing motion blur with the excess frames that are captured with e.g. a Game Capture source.

People have been doing this effect for video game footage in post with NLEs for years, and a filter doing it before it even gets encoded would eliminate the huge burden of encoding, storing and processing high framerate footage.

The earliest mention of something like this in OBS: <https://ideas.obsproject.com/posts/835/add-frame-blending-option-to-game-capture-faux-motion-blur>

I generated an OBS plugin template that has the same goal, and in the README linked a bunch of implementations in other software for people to get familiar with the concept:

https://github.com/couleurm/smooth-mode

**Comment by FiniteSingularity** [comment]
Sounds like a great idea.  I'd bring this in as a "temporal" blur option.  To do this, we'd need to add an option for a prior number of frames to blur in.  I'd also think it'd be worth having different options for the weighted average of the prior frames, e.g.- Uniform, Linear falloff, exponential falloff, etc.  I think I might be able to use an algorithm similar to what I used with the BSM Alpha Wipe do do this efficiently.

**Comment by couleurm** [comment]
we're discussing a lua script that blends frames in https://github.com/couleurm/smooth-mode/issues/2 if you're curious

**Comment by FiniteSingularity** [comment]
Good stuff! I'm currently in the process of revisiting Composite blur (just added some new pixelate effects, and vector blur), and temporal blur is next on my list of things to tackle. Sorry it took me so long to get back to Composite blur, but hopefully we'll have something working shortly!

**Comment by FiniteSingularity** [comment]
Looking through some notes I took on this back in June.

There are a couple of ways to approach this.  The simplest is using the equivalent of a box blur (each frame gets the same weight, and we just average the last `n` frames, where `n` is a value set by the user.  This is easy, as we can subtract off the first frame in the average, and add in the new frame (so we only have to blend 3 frames, instead of `n` frames.

More complex, would be to do something like a Gaussian convolution.  A naive approach would require re-blending all of the frames every step. That said, a Gaussian function is self-similar, so there should be a way to do a self-similar convolution, which would average out the older frames until they are essentially no longer factored in.  I think this could lead to a very high quality temporal blur, with very low overhead.

**Comment by FiniteSingularity** [comment]
Added in #113
