### ISSUE TITLE
[BUG] - Package does not pass notarization requirements for macOS Sequoia 

### ISSUE THREAD

**Issue by felipemullen** [FiniteSingularity/obs-composite-blur#115]
**Describe the bug**
Attempting to install the `.pkg` file in MacOS 15.x will fail due to notarization

**To Reproduce**
1. Download latest for MacOS
2. Attempt to run `.pkg` installer
3. See install error

**Expected behavior**
The package should open normally

**Screenshots**

![image](https://github.com/user-attachments/assets/f25f33a8-44e2-409e-83f8-8cc76e57016c)

**Environment**
 - OS/Version: MacOS Sequoia 15.0.1

**Workaround**

1. Open `Settings`
2. Go to `Privacy and Security`
3. Scroll to `Security`
4. Click on `Open Anyway`

![image](https://github.com/user-attachments/assets/5e342382-3aae-48cf-bb12-bff9fd1322ef)

**Comment by FiniteSingularity** [comment]
Hi @felipemullen,

Thank you for the issue.  Yes, this is an issue, and it requires paying for an Apple Developer Account. I'm working on getting the funds and a dev account set up so that the plugins can be signed.  I already have an issue open for this ( #72 ) so I'll close this one, but feel free to track it over there.
