### ISSUE TITLE
[BUG] - Attempting to apply filter causes the source to blank out

### ISSUE THREAD

**Issue by LividJava** [FiniteSingularity/obs-composite-blur#47]
**Describe the bug**
When applying the Filter, the targeted source will go black and produce an error in OBS log.

**To Reproduce**
1. Attempt to apply the Gaussian Filter
2. Encounter an error where the source blanks out.

**Expected behavior**
The filter would be applied as normal.

**Environment**
 - OS/Version: Windows 10 Pro 22H2 (19045.3324)
 - OBS Version: 29.1.3
 - Composite Blur Plugin Version: 1.0.1
 - Blur Algorithm/Type: Gaussian

**GPU**
 - GPU make/model: MSI AMD RX 480
 - GPU VRAM: 8GB

**Additional context**
Other Blur effects appear as normal

<details>
<summary>Relevant Error</summary>

02:42:20.891: User added filter 'Composite Blur' (obs_composite_blur) to source 'Waveform Visualizer'
02:42:20.908: Error compiling shader:
02:42:20.908: ERROR: 0:40: 'expression' :  left of '[' is not of type array, matrix, or vector  
02:42:20.908: ERROR: 0:40: '' : compilation terminated 
02:42:20.908: ERROR: 2 compilation errors.  No code generated.
02:42:20.908: 
02:42:20.908: 
02:42:20.908: 
02:42:20.908: device_pixelshader_create (GL) failed
02:42:20.908: Pass (0) <> missing pixel shader!
02:42:20.908: [obs-composite-blur] Unable to load .effect file.  Errors:
02:42:20.908: (None)
</details>

**Comment by FiniteSingularity** [comment]
Hi @LividJava-

Thank you for opening the issue, and for providing the error log.  That error occurs looks like you're using an OpenGL renderer rather than Direct3D, but you are on a Windows system. There is a special set of Gaussian shader effect files for operating systems that use OpenGL as their renderer (Linux and MacOS), but Windows uses Direct3D (and so the Windows build does not use the shader effect files with the OpenGL fix).

Do you happen to know if you're forcing OpenGL on Windows (by adding `--allow-opengl` to your OBS launch)?  Alternatively, can you please let me know what you see in `Settings --> Advanced --> Video --> Renderer`?  e.g.-

![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/72580859/9930edd2-8724-469a-ba6b-b60c7559b18b)

**Comment by FiniteSingularity** [comment]
@LividJava-

I think I've got a fix ready to go, and would really appreciate if you could give it a test and see if it fixes the problem for you.  If you're able to give it a try- go to the PRs action run page ( https://github.com/FiniteSingularity/obs-composite-blur/actions/runs/6137256282 ) and scroll down to the bottom.  You'll see a section called "Artifacts".  Download one of the two Windows zip files (either installer or the normal zip).  Make sure your OBS has been quit, and install the new version of the plugin, run OBS, and let me know if it resolves the issue.

**Comment by FiniteSingularity** [comment]
The merged PR should have fixed this issue.  It'll be included in release 1.0.2, which I'm going to release in an hour or two.  Please re-open if v1.0.2 doesn't resolve your issue @LividJava.

**Comment by FiniteSingularity** [comment]
@all-contributors please add @LividJava for bug

**Comment by LividJava** [comment]
hopefully this comment doesn't reopen the issue. I imported a config file over from linux to windows, it also apparently carried over the opengl setting. on 1.0.1 switching over to the Direct3D renderer does fix the issue. and on 1.0.2 using OpenGL the issue is fixed as well. Apologies for the late response, i've just been really busy

**Comment by FiniteSingularity** [comment]
No worries on the delay.  I’m glad it fixed the issue!
