### ISSUE TITLE
[BUG] - Masking with source alpha not working as expected

### ISSUE THREAD

**Issue by ASchneiderBR** [FiniteSingularity/obs-composite-blur#49]
## Describe the bug

When using the Composite Blur filter and trying to mask using a source with alpha information, the mask does not work as expected. 

## To Reproduce

1. Add an image source with chroma key filters applied to create transparency
2. Add a 1080p video source to blur
3. Add Composite Blur filter to video source
4. Set Composite Blur to mask using the image source
5. The mask has no effect on the blur

## Expected behavior

I expected the alpha channel of the image source to properly mask the blur effect on the video source.

## Screenshots

https://streamable.com/65y76i

## Environment

- OS/Version: Windows 11
- OBS Version: 30 beta
- Composite Blur Plugin Version: 1.0.1
- Blur Algorithm/Type: Dual Kawase, Area

## GPU

- GPU: Nvidia RTX 2080 Ti
- VRAM: 11Gb

## Additional context

I am scaling a 4K PNG image source with transparency down to 1080p using chroma key filters, and attempting to use it to mask blur on a 1080p video source. It seems like the mask functionality is not working properly in this case.

**Comment by FiniteSingularity** [comment]
Hi @ASchneiderBR-

Thank you for the fantastic issue report (I very much appreciate the linked video that clearly shows the issue).  I was easily able to replicate the issue, and am seeing the same thing you see.  It seems to be unique to the image source (other source types seem to work fine with chroma keying).  I'll dive into this and try to find out a fix.

In the meantime, I was able to find a workaround:

1. Create a new empty scene, call it `Keyed Image Scene`
2. Add your image to the new scene, call it `Keyed Image`
3. Apply the chroma key to the **image source** like before.
4. For the source you want to mask blur on, select `Keyed Image Scene` for the masking source instead of the original image source.
5. You should now see a proper mask using the chroma keyed image.

For some reason, having the image embedded in a scene allows the alpha information to come through, while selecting just the image source does not.

**Comment by FiniteSingularity** [comment]
Found the issue, and have a fix on the way.  Will try to merge in this afternoon, and combine with the fix for #47 and release a new version.

**Comment by ASchneiderBR** [comment]
Thank you very much! AI is just amazing for creating issues as I recently discovered :) I'm glad I could help in any way, your plugin is just incredible and deserves all of the best. Have a great day!

**Comment by FiniteSingularity** [comment]
@all-contributers please add @ASchneiderBR for bug

**Comment by FiniteSingularity** [comment]
@all-contributors please add @ASchneiderBR for bug
