### ISSUE TITLE
[BUG] - Can't find filter in OBS for macOS

### ISSUE THREAD

**Issue by jimmy-robert** [FiniteSingularity/obs-composite-blur#60]
**Describe the bug**

Hello ! I run OBS on a Mac Studio M1 Max. I installed the universal version, and then tried the arm64 version from last release, but I can't find the filter in OBS after installing plugin.

**To Reproduce**

1. Install plugin
2. Filter not available

**Expected behavior**

Find the composite blur filter from the filter list.

**Environment**
 - OS/Version: macOS Ventura
 - OBS Version: 29.1.3
 - Composite Blur Plugin Version: 1.0.2

**Comment by FiniteSingularity** [comment]
Hi @jimmy-robert.

I'm sorry to hear you're having an issue with the plugin installation on a Mac.  The good news is, I've got an M1 Pro Mac as well, so we should be able to figure this out.  I suspect that the installer didn't install the plugin properly.  Can you please let me know if the plugin is in your OBS plugins directory?  To check, in the MacOS Finder:
1. Hold down the `option` key, and select `Library` from the `Go` menu.
2. This will open a finder window.  Open the `Application Support` folder, then `obi-studio`, then `plugins`.

Do you see a file called `obs-composite-blur.plugin`?

**Comment by jimmy-robert** [comment]
Hi! Yes I can see the file `obs-composite-blur.plugin` in `/Library/Application Support/obs-studio/plugins`. 

I tried to delete the file and reinstall the plugin, I also tried to restart my mac, but nothing changed 🫤

**Comment by FiniteSingularity** [comment]
Just to confirm- you're seeing the plugin in the hard drive root `/Library/Application Support` directory?  not in your user level `/Users/<your user name>/Library/Application Support/obs-studio/plugins`?

**Comment by FiniteSingularity** [comment]
I suspect I know what is going on.  @jimmy-robert did you select "install for all users" instead of "install for just this user" with the installer?  It looks like OBS made a change where on Apple Silicon Macs, they're requiring that plugins be loaded from the user's library (at least if I'm reading this PR correctly: https://github.com/obsproject/obs-studio/pull/7089 ).  @exeldro, if I'm reading that correctly, it looks like we should disable the "install for all users" option, as it installs the plugin in `/Library` rather than `/Users/<username>/Library` which won't be loaded by OBS.

**Comment by jimmy-robert** [comment]
I just copied the plugin file in the `/Users/Library` directory and it works!

Thank you!

**Comment by FiniteSingularity** [comment]
Glad to hear it works!  I'll need to take a look at the Mac installer and fix it to keep this from happening.  If you need to install an update, make sure to select the "only for this user" option as it will properly install it in your user library instead of the root library.
